default:
  DEBUG: True
  DATABASES__default__ENGINE:
  DATABASES__default__NAME:
  DATABASES__default__USER:
  DATABASES__default__PASSWORD:
  DATABASES__default__HOST:
  DATABASES__default__PORT:
  ALLOWED_HOSTS:
    - "*"
  STATIC_ROOT: ./static
  STATIC_URL: /static/
  ROOT_URLCONF: admin_pannel.urls
  TEMPLATES:
    - BACKEND: django.template.backends.django.DjangoTemplates
      DIRS: [ ]
      APP_DIRS: true
      OPTIONS:
        context_processors:
          - django.template.context_processors.debug
          - django.template.context_processors.request
          - django.contrib.auth.context_processors.auth
          - django.contrib.messages.context_processors.messages

development:
  DEBUG: True
  DATABASES__default__ENGINE: django.db.backends.postgresql
  DATABASES__default__NAME: measurement-system
  DATABASES__default__USER: admin
  DATABASES__default__PASSWORD: admin
  DATABASES__default__HOST: localhost
  DATABASES__default__PORT: 5432

#production:
#  DEBUG: false

testing:
